alter table SUPPLY_QUERIES_POSITION add constraint FK_SUPPLY_QUERIES_POSITION_QUERY foreign key (QUERY_ID) references SUPPLY_QUERY(ID);
alter table SUPPLY_QUERIES_POSITION add constraint FK_SUPPLY_QUERIES_POSITION_NOMENCLATURE foreign key (NOMENCLATURE_ID) references SUPPLY_NOMENCLATURE(ID);
alter table SUPPLY_QUERIES_POSITION add constraint FK_SUPPLY_QUERIES_POSITION_MEASURE_UNIT foreign key (MEASURE_UNIT_ID) references SUPPLY_MEASURE_UNITS(ID);
create index IDX_SUPPLY_QUERIES_POSITION_QUERY on SUPPLY_QUERIES_POSITION (QUERY_ID);
create index IDX_SUPPLY_QUERIES_POSITION_NOMENCLATURE on SUPPLY_QUERIES_POSITION (NOMENCLATURE_ID);
create index IDX_SUPPLY_QUERIES_POSITION_MEASURE_UNIT on SUPPLY_QUERIES_POSITION (MEASURE_UNIT_ID);
