alter table SUPPLY_ANALOGS add constraint FK_SUPPLY_ANALOGS_NOMENCLATURE foreign key (NOMENCLATURE_ID) references SUPPLY_NOMENCLATURE(ID);
alter table SUPPLY_ANALOGS add constraint FK_SUPPLY_ANALOGS_ANALOG foreign key (ANALOG_ID) references SUPPLY_NOMENCLATURE(ID);
create index IDX_SUPPLY_ANALOGS_NOMENCLATURE on SUPPLY_ANALOGS (NOMENCLATURE_ID);
create index IDX_SUPPLY_ANALOGS_ANALOG on SUPPLY_ANALOGS (ANALOG_ID);
