alter table SUPPLY_DIVISION add constraint FK_SUPPLY_DIVISION_COMPANY foreign key (COMPANY_ID) references SUPPLY_COMPANY(ID);
create index IDX_SUPPLY_DIVISION_COMPANY on SUPPLY_DIVISION (COMPANY_ID);
