alter table SUPPLY_NOMENCLATURE add constraint FK_SUPPLY_NOMENCLATURE_UNIT foreign key (UNIT_ID) references SUPPLY_MEASURE_UNITS(ID);
create index IDX_SUPPLY_NOMENCLATURE_UNIT on SUPPLY_NOMENCLATURE (UNIT_ID);
