alter table SUPPLY_QUERIES_POSITION add constraint FK_SUPPLY_QUERIES_POSITION_STORE foreign key (STORE_ID) references SUPPLY_STORE(ID);
create index IDX_SUPPLY_QUERIES_POSITION_STORE on SUPPLY_QUERIES_POSITION (STORE_ID);
