alter table SUPPLY_BILLS add constraint FK_SUPPLY_BILLS_ON_SUPPLIER foreign key (SUPPLIER_ID) references SUPPLY_SUPPLIERS(ID);
create index IDX_SUPPLY_BILLS_ON_SUPPLIER on SUPPLY_BILLS (SUPPLIER_ID);
