alter table SUPPLY_PROCURATION add constraint FK_SUPPLY_PROCURATION_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references SUPPLY_EMPLOYEE(ID);
create unique index IDX_SUPPLY_PROCURATION_UK_NUMBER_ on SUPPLY_PROCURATION (NUMBER_) where DELETE_TS is null ;
create index IDX_SUPPLY_PROCURATION_ON_EMPLOYEE on SUPPLY_PROCURATION (EMPLOYEE_ID);
