alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_MEASURE_UNITS foreign key (MEASURE_UNITS_ID) references SUPPLY_MEASURE_UNITS(ID);
create index IDX_SUPPLY_SETTINGS_ON_MEASURE_UNITS on SUPPLY_SETTINGS (MEASURE_UNITS_ID);
