create table SUPPLY_QUERY_POSITION_STAGE_DATA_ITEM_LINK (
    QUERY_POSITION_STAGE_DATA_ID uuid,
    QUERY_POSITION_STAGE_DATA_ITEM_ID uuid,
    primary key (QUERY_POSITION_STAGE_DATA_ID, QUERY_POSITION_STAGE_DATA_ITEM_ID)
);
