alter table SUPPLY_SETTINGS rename column supply_workout_type to supply_workout_type__u06420 ;
alter table SUPPLY_SETTINGS rename column stages to stages__u67406 ;
alter table SUPPLY_SETTINGS rename column query_status to query_status__u27497 ;
alter table SUPPLY_SETTINGS rename column position_type to position_type__u25769 ;
alter table SUPPLY_SETTINGS rename column peridiocities to peridiocities__u40217 ;
alter table SUPPLY_SETTINGS rename column origin to origin__u47375 ;
alter table SUPPLY_SETTINGS rename column causes to causes__u38284 ;
alter table SUPPLY_SETTINGS rename column cargo_state to cargo_state__u98283 ;
alter table SUPPLY_SETTINGS rename column analysis_result to analysis_result__u26477 ;
alter table SUPPLY_SETTINGS rename column division_id to division_id__u75809 ;
drop index IDX_SUPPLY_SETTINGS_ON_DIVISION ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_DIVISION ;
alter table SUPPLY_SETTINGS rename column suppliers_id to suppliers_id__u69812 ;
drop index IDX_SUPPLY_SETTINGS_ON_SUPPLIERS ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_SUPPLIERS ;
alter table SUPPLY_SETTINGS rename column company_id to company_id__u64447 ;
drop index IDX_SUPPLY_SETTINGS_ON_COMPANY ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_COMPANY ;
alter table SUPPLY_SETTINGS rename column holiday_id to holiday_id__u40558 ;
drop index IDX_SUPPLY_SETTINGS_ON_HOLIDAY ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_HOLIDAY ;
alter table SUPPLY_SETTINGS rename column employee_id to employee_id__u21441 ;
drop index IDX_SUPPLY_SETTINGS_ON_EMPLOYEE ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_EMPLOYEE ;
alter table SUPPLY_SETTINGS rename column delivery_line_id to delivery_line_id__u60623 ;
drop index IDX_SUPPLY_SETTINGS_ON_DELIVERY_LINE ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_DELIVERY_LINE ;
alter table SUPPLY_SETTINGS rename column delivery_id to delivery_id__u51348 ;
drop index IDX_SUPPLY_SETTINGS_ON_DELIVERY ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_DELIVERY ;
alter table SUPPLY_SETTINGS rename column bills_id to bills_id__u42901 ;
drop index IDX_SUPPLY_SETTINGS_ON_BILLS ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_BILLS ;
alter table SUPPLY_SETTINGS rename column analogs_id to analogs_id__u83413 ;
drop index IDX_SUPPLY_SETTINGS_ON_ANALOGS ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_ANALOGS ;
alter table SUPPLY_SETTINGS rename column positions_analogs_id to positions_analogs_id__u52494 ;
drop index IDX_SUPPLY_SETTINGS_ON_POSITIONS_ANALOGS ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_POSITIONS_ANALOGS ;
alter table SUPPLY_SETTINGS rename column position_supplier_id to position_supplier_id__u70227 ;
drop index IDX_SUPPLY_SETTINGS_ON_POSITION_SUPPLIER ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_POSITION_SUPPLIER ;
alter table SUPPLY_SETTINGS rename column nomenclature_id to nomenclature_id__u20068 ;
drop index IDX_SUPPLY_SETTINGS_ON_NOMENCLATURE ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_NOMENCLATURE ;
alter table SUPPLY_SETTINGS rename column vote_id to vote_id__u60917 ;
drop index IDX_SUPPLY_SETTINGS_ON_VOTE ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_VOTE ;
alter table SUPPLY_SETTINGS rename column urgency_id to urgency_id__u95991 ;
drop index IDX_SUPPLY_SETTINGS_ON_URGENCY ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_URGENCY ;
alter table SUPPLY_SETTINGS rename column suppliers_suggestion_id to suppliers_suggestion_id__u28707 ;
drop index IDX_SUPPLY_SETTINGS_ON_SUPPLIERS_SUGGESTION ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_SUPPLIERS_SUGGESTION ;
alter table SUPPLY_SETTINGS rename column store_id to store_id__u09261 ;
drop index IDX_SUPPLY_SETTINGS_ON_STORE ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_STORE ;
alter table SUPPLY_SETTINGS rename column stage_term_id to stage_term_id__u76815 ;
drop index IDX_SUPPLY_SETTINGS_ON_STAGE_TERM ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_STAGE_TERM ;
alter table SUPPLY_SETTINGS rename column query_workflow_detail_id to query_workflow_detail_id__u48354 ;
drop index IDX_SUPPLY_SETTINGS_ON_QUERY_WORKFLOW_DETAIL ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_QUERY_WORKFLOW_DETAIL ;
alter table SUPPLY_SETTINGS rename column query_workflow_id to query_workflow_id__u58108 ;
drop index IDX_SUPPLY_SETTINGS_ON_QUERY_WORKFLOW ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_QUERY_WORKFLOW ;
alter table SUPPLY_SETTINGS rename column query_position_stage_data_item_id to query_position_stage_data_item_id__u55178 ;
drop index IDX_SUPPLY_SETTINGS_ON_QUERY_POSITION_STAGE_DATA_ITEM ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_QUERY_POSITION_STAGE_DATA_ITEM ;
alter table SUPPLY_SETTINGS rename column query_position_stage_data_id to query_position_stage_data_id__u14600 ;
drop index IDX_SUPPLY_SETTINGS_ON_QUERY_POSITION_STAGE_DATA ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_QUERY_POSITION_STAGE_DATA ;
alter table SUPPLY_SETTINGS rename column query_position_movements_id to query_position_movements_id__u90514 ;
drop index IDX_SUPPLY_SETTINGS_ON_QUERY_POSITION_MOVEMENTS ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_QUERY_POSITION_MOVEMENTS ;
alter table SUPPLY_SETTINGS rename column query_id to query_id__u94392 ;
drop index IDX_SUPPLY_SETTINGS_ON_QUERY ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_QUERY ;
alter table SUPPLY_SETTINGS rename column queries_position_id to queries_position_id__u49042 ;
drop index IDX_SUPPLY_SETTINGS_ON_QUERIES_POSITION ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_QUERIES_POSITION ;
alter table SUPPLY_SETTINGS rename column procuration_id to procuration_id__u25776 ;
drop index IDX_SUPPLY_SETTINGS_ON_PROCURATION ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_PROCURATION ;
alter table SUPPLY_SETTINGS rename column measure_units_id to measure_units_id__u21952 ;
drop index IDX_SUPPLY_SETTINGS_ON_MEASURE_UNITS ;
alter table SUPPLY_SETTINGS drop constraint FK_SUPPLY_SETTINGS_ON_MEASURE_UNITS ;
