alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_URGENCY foreign key (URGENCY_ID) references SUPPLY_URGENCY(ID);
create index IDX_SUPPLY_SETTINGS_ON_URGENCY on SUPPLY_SETTINGS (URGENCY_ID);
