alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_DELIVERY_LINE foreign key (DELIVERY_LINE_ID) references SUPPLY_DELIVERY_LINE(ID);
create index IDX_SUPPLY_SETTINGS_ON_DELIVERY_LINE on SUPPLY_SETTINGS (DELIVERY_LINE_ID);
