alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_DELIVERY foreign key (DELIVERY_ID) references SUPPLY_DELIVERY(ID);
create index IDX_SUPPLY_SETTINGS_ON_DELIVERY on SUPPLY_SETTINGS (DELIVERY_ID);
