alter table SUPPLY_QUERIES_POSITION add constraint FK_SUPPLY_QUERIES_POSITION_ON_DELIVERY foreign key (DELIVERY_ID) references SUPPLY_DELIVERY(ID);
create index IDX_SUPPLY_QUERIES_POSITION_ON_DELIVERY on SUPPLY_QUERIES_POSITION (DELIVERY_ID);
