create table SUPPLY_SETTINGS (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    KEY_ varchar(50) not null,
    SAVED_OBJECT text,
    MEASURE_UNITS_ID uuid,
    PROCURATION_ID uuid,
    QUERIES_POSITION_ID uuid,
    QUERY_ID uuid,
    QUERY_POSITION_MOVEMENTS_ID uuid,
    QUERY_POSITION_STAGE_DATA_ID uuid,
    QUERY_POSITION_STAGE_DATA_ITEM_ID uuid,
    QUERY_WORKFLOW_ID uuid,
    QUERY_WORKFLOW_DETAIL_ID uuid,
    STAGE_TERM_ID uuid,
    STORE_ID uuid,
    SUPPLIERS_SUGGESTION_ID uuid,
    URGENCY_ID uuid,
    VOTE_ID uuid,
    NOMENCLATURE_ID uuid,
    POSITION_SUPPLIER_ID uuid,
    POSITIONS_ANALOGS_ID uuid,
    ANALOGS_ID uuid,
    BILLS_ID uuid,
    DELIVERY_ID uuid,
    DELIVERY_LINE_ID uuid,
    EMPLOYEE_ID uuid,
    HOLIDAY_ID uuid,
    COMPANY_ID uuid,
    SUPPLIERS_ID uuid,
    TEXT varchar(50),
    BOOLEAN_VALUE boolean,
    DIVISION_ID uuid,
    BIG_DECIMAL_VALUE decimal(19, 2),
    DATE_TIME_VALUE timestamp,
    DATE_VALUE date,
    DOUBLE_VALUE double precision,
    INTEGER_VALUE integer,
    LONG_VALUE bigint,
    TIME_VALUE time,
    ANALYSIS_RESULT varchar(50),
    CARGO_STATE varchar(50),
    CAUSES varchar(50),
    ORIGIN varchar(50),
    PERIDIOCITIES varchar(50),
    POSITION_TYPE varchar(50),
    QUERY_STATUS varchar(50),
    STAGES varchar(50),
    SUPPLY_WORKOUT_TYPE varchar(50),
    --
    primary key (ID)
);
