alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_NOMENCLATURE foreign key (NOMENCLATURE_ID) references SUPPLY_NOMENCLATURE(ID);
create index IDX_SUPPLY_SETTINGS_ON_NOMENCLATURE on SUPPLY_SETTINGS (NOMENCLATURE_ID);
