alter table supply_queries_position_token_link rename to SUPPLY_QUERIES_POSITION_TOKEN_LINK__U97287 ;
alter table supply_queries_position_token_link_queries_position_link drop constraint FK_QUEPOSTOKLINQUEPOS_ON_QUERIES_POSITION_TOKEN_LINK ;
