alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_HOLIDAY foreign key (HOLIDAY_ID) references SUPPLY_HOLIDAY(ID);
create index IDX_SUPPLY_SETTINGS_ON_HOLIDAY on SUPPLY_SETTINGS (HOLIDAY_ID);
