alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_DIVISION foreign key (DIVISION_ID) references SUPPLY_DIVISION(ID);
create index IDX_SUPPLY_SETTINGS_ON_DIVISION on SUPPLY_SETTINGS (DIVISION_ID);
