create table SUPPLY_QUERIES_POSITION_TOKEN_LINK_QUERIES_POSITION_LINK (
    QUERIES_POSITION_TOKEN_LINK_ID uuid,
    QUERIES_POSITION_ID uuid,
    primary key (QUERIES_POSITION_TOKEN_LINK_ID, QUERIES_POSITION_ID)
);
