alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_COMPANY foreign key (COMPANY_ID) references SUPPLY_COMPANY(ID);
create index IDX_SUPPLY_SETTINGS_ON_COMPANY on SUPPLY_SETTINGS (COMPANY_ID);
