alter table SUPPLY_DELIVERY_LINE add constraint FK_SUPPLY_DELIVERY_LINE_ON_DELIVERY foreign key (DELIVERY_ID) references SUPPLY_DELIVERY(ID);
create index IDX_SUPPLY_DELIVERY_LINE_ON_DELIVERY on SUPPLY_DELIVERY_LINE (DELIVERY_ID);
