alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references SUPPLY_EMPLOYEE(ID);
create index IDX_SUPPLY_SETTINGS_ON_EMPLOYEE on SUPPLY_SETTINGS (EMPLOYEE_ID);
