alter table SUPPLY_SETTINGS add constraint FK_SUPPLY_SETTINGS_ON_PROCURATION foreign key (PROCURATION_ID) references SUPPLY_PROCURATION(ID);
create index IDX_SUPPLY_SETTINGS_ON_PROCURATION on SUPPLY_SETTINGS (PROCURATION_ID);
