alter table SUPPLY_BILLS add constraint FK_SUPPLY_BILLS_ON_COMPANY foreign key (COMPANY_ID) references SUPPLY_COMPANY(ID);
alter table SUPPLY_BILLS add constraint FK_SUPPLY_BILLS_ON_SUPPLIER foreign key (SUPPLIER_ID) references SUPPLY_SUPPLIERS(ID);
alter table SUPPLY_BILLS add constraint FK_SUPPLY_BILLS_ON_IMAGE_BILL foreign key (IMAGE_BILL_ID) references SYS_FILE(ID);
create unique index IDX_SUPPLY_BILLS_UK_NUMBER_ on SUPPLY_BILLS (NUMBER_) where DELETE_TS is null ;
create index IDX_SUPPLY_BILLS_ON_COMPANY on SUPPLY_BILLS (COMPANY_ID);
create index IDX_SUPPLY_BILLS_ON_SUPPLIER on SUPPLY_BILLS (SUPPLIER_ID);
create index IDX_SUPPLY_BILLS_ON_IMAGE_BILL on SUPPLY_BILLS (IMAGE_BILL_ID);
